// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Sharky":return img`
..........fffcc...fffffff...........
..........fbbbbcffbbbbbbbf..........
...........fbffbbbbb111bbf..........
...........ffbbbbff11111bf..........
.........ffcbbbbbff1cccc1f..........
........fcccbcbcbb1c1c1cff..........
ccccc..fcccbcbcbbb1333ccf...........
cbbddcfccccbcbcbbb1c333c............
.ccbddcccccbbbbbbb1c333c............
..ccbbccccccbbbbb11c333c............
..fccbfccccccbbbb11c133cc...........
..fccfcbbcccccbbbc11c31cc...........
.fcbbf.cdddddfbbbc111111c...........
.fbbf...cdddfbbdbf1111cc............
fbbf.....ccfbbdbfffccc..............
fff........fffff....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
